#!/bin/bash

pushd $PWD/docker/base
docker build -t ioos/ckanext-ioos-theme:base .
popd
pushd $PWD/docker/ckan
docker build -t ioos/ckanext-ioos-theme:ckan .
popd
pushd $PWD/docker/pycsw
docker build -t ioos/ckanext-ioos-theme:pycsw .
popd
pushd $PWD/docker/harvester
docker build -t ioos/ckanext-ioos-theme:harvester .
popd
