#!/bin/bash
set -eu
: ${CKAN_INIT:=}

if [[ -n "$CKAN_INIT"  && "$CKAN_INIT" == "true" ]]; then
    "$CKAN_HOME"/bin/paster --plugin=ckan db init -c "${CKAN_CONFIG}/ckan.ini"
    "$CKAN_HOME"/bin/paster --plugin=ckanext-spatial spatial initdb -c "${CKAN_CONFIG}/ckan.ini"
    "$CKAN_HOME"/bin/paster --plugin=ckanext-harvest harvester initdb -c "${CKAN_CONFIG}/ckan.ini"
fi

